# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

parameters:
- name: name
  displayName: 'name:'
  type: string
  default: false

jobs:
- job: 'CallFunction'
  pool: server
  steps:
  - task: AzureFunction@1
    inputs:
      function: 'https://wvd-scale.azurewebsites.net/api/DeploymentRequestProcess'
      key: '$(functionKey)'
      method: 'POST'
      body: |
        {
        "name":${{ parameters.image }}
        }
      waitForCompletion: 'false'